name: Code testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort pylint black mypy flake8 pytest pytest-cov scikit-learn
          pip install -e .
      - name: isort
        run: |
          isort -c .
      - name: flake8
        run: |
          flake8 .
      - name: mypy
        run: |
          mypy .
      - name: black
        run: |
          black .
      - name: pytest
        run: |
          pytest
      - name: pylint
        run: |
          pylint .